### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by zhushaofeng1992** [PrincetonUniversity/ILAng#214]
**Describe the bug**
when build the ILAng, at the make step, it reports ILAng/include/ilang/util/container.h:67:10: error: expected unqualified-id before '[' token
               auto [it,status] =map_.try_emplace(key,idx);

**To Reproduce**
1. Go to 'building from source'
2. execute 'mkdir -p build && cd build
                   cmake ..  
                   make -j$(nproc)'
3. See error then see the error

**Environment (please complete the following information):**

-   OS: [Ubuntu 16.04]
-   Compiler [gcc 5.4.0, cmake 3.19.5]
-   Other dependencies [z3 4.4.1]

**Additional context**

**Comment by Bo-Yuan-Huang** [comment]
ILAng requires CMake (3.9.6 or above) and compilers with C++17 support, and other [prerequisites](https://github.com/PrincetonUniversity/ILAng#prerequisites). 
Please check [structured binding](https://en.cppreference.com/w/cpp/language/structured_binding) and [gcc/g++](https://gcc.gnu.org/projects/cxx-status.html#cxx17) support for C++ standard for further detail.
