### ISSUE TITLE
Fix the link to API reference

### ISSUE THREAD

**Issue by zhanghongce** [PrincetonUniversity/ILAng#216]
**Describe the bug**
The link to the API reference in README.md is broken after repo migration, namely the link `https://bo-yuan-huang.github.io/ILAng-Doc/doxygen-output-html/namespaceilang.html` is no longer valid.

**To Reproduce**
1. Click the `docs:doxygen` badge in README.md

Discussion: ILAng-Doc is no longer hosted under Bo-Yuan's name. However, I don't know if the university has a corresponding `github.io` link for use.

**Comment by yuex1994** [comment]
Thanks for noticing this -- https://github.com/PrincetonUniversity/ILAng/pull/212 should fix this, but it has not been merged yet.

**Comment by zhanghongce** [comment]
Thanks, Yue!
